name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Conditionally Install Yarn for local Github Actions Emulator ACT
        if: ${{ env.ACT }}
        run: npm -g install yarn

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "web/yarn.lock"

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/cache
            web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('web/yarn.lock') }}-${{ hashFiles('web/src/**/*.js', 'web/src/**/*.jsx', 'web/src/**/*.ts', 'web/src/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('web/yarn.lock') }}-

      - name: Install dependencies
        working-directory: "./web"
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: "./web"
        run: yarn build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_OSL_EVENTS_APP }}
          channelId: live
          projectId: osl-events-app
          entryPoint: "web"
          target: hosting
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
