name: Monitoring and Alerts
on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch:

jobs:
  monitoring:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@v1
        with:
          version: latest
          token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          organization: vike
          project: vike-web

      - name: Check Sentry Issues
        run: |
          sentry-cli issues list --status=unresolved
